### ISSUE TITLE
Update default form confirmation style

### ISSUE THREAD

**Issue by bholaday** [PurdueAlumniAssociation/purduealumni.org#117]
Add a more apparent, green confirmation message box.

**Comment by bholaday** [comment]
Let's mimic Bootstraps alert: https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by gabbumms** [comment]
Not sure what page this is referring to or if there is already a file for this? I found this but couldn't find if there was a certain scss file I should be editing? Let me know! Thank you (:
![Screen Shot 2019-04-29 at 10 12 17 AM](https://user-images.githubusercontent.com/47796367/56902022-6c243a00-6a67-11e9-937d-8019fc981b23.png)

**Comment by bholaday** [comment]
No need to change any of the template files for this one. It is a purely css addition. We need to add some styles to: `src/sass/elements/form/gravityforms-overrides`

Here's an example of the default code for a confirmation message:
```
<div id="gform_confirmation_wrapper_1" class="gform_confirmation_wrapper ">
  <div id="gform_confirmation_message_1" class="gform_confirmation_message_1 gform_confirmation_message">
   Thanks for contacting us! We will get in touch with you shortly.
  </div>
</div>
```

**Comment by bholaday** [comment]
Closing #117. 

I already did this. Whoops!
